---
apiVersion: v1
kind: Service
metadata:
  name: netology-service
spec:
  ports:
    - name: netology-nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: netology-multitool
      port: 8080
      protocol: TCP
      targetPort: 1180
  selector:
    app: my-app