---
apiVersion: v1
kind: Service
metadata:
  name: multinginx
spec:
  selector:
    app: multinginx-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  tls:
    - hosts:
      - test.local
      secretName: my-tls-secret
  rules:
    - host: test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multinginx
                port:
                  number: 80
