---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse 

- src: git@github.com:LexNezv/vector-role.git
  scm: git
  name: vector-role 

- src: git@github.com:LexNezv/lighthouse-role.git
  scm: git
  name: lighthouse-role 