
stages:
  - build
  - test

variables:
  IMAGE_NAME: hello:gitlab-$CI_COMMIT_SHORT_SHA
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/$IMAGE_NAME

build:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker-dind
  stage: build
  tags:
    - privileged
  variables:
    DOCKER_HOST: tcp://docker-dind:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REGISTRY_IMAGE
    - docker push $REGISTRY_IMAGE
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

test:
  image: alpine/curl
  services:
    - name: $REGISTRY_IMAGE
      alias: python-api
  stage: test
  tags:
    - privileged
  script:
    - curl http://python-api:5290/get_info