---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb
            dest: "{{ download_path }}/{{ item }}-{{ clickhouse_version }}.deb"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "{{ download_path }}/clickhouse-common-static-{{ clickhouse_version }}.deb"

    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ download_path }}/clickhouse-common-static-{{ clickhouse_version }}.deb"
          #- ./clickhouse-client-{{ clickhouse_version }}.deb
          #- ./clickhouse-server-{{ clickhouse_version }}.deb
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: clickhouse-client -q 'create database logs;'
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install vector
  hosts: vector
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url: 
        url: https://packages.timber.io/vector/0.35.0/vector_0.35.0-1_arm64.deb
        dest: ./vector_0.35.0-1_arm64.deb
