---
all:
  hosts:
    sonar-01:
      ansible_host: 192.168.56.102
    nexus-01:
      ansible_host: 192.168.56.103
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant